/**
 * Traces public/logo.png into three vector path layers (rough circle,
 * "mz" initials, flame) so the logo can be rendered and animated as SVG.
 *
 * Usage: node scripts/trace-logo.js
 * Output: src/components/ui/logo-paths.ts + debug layer PNGs in scripts/debug/
 */
const fs = require("fs");
const path = require("path");
const potrace = require("potrace");
const Jimp = require("jimp");

const SRC = path.join(__dirname, "..", "public", "logo.png");
const OUT = path.join(__dirname, "..", "src", "components", "ui", "logo-paths.ts");
const DEBUG_DIR = path.join(__dirname, "debug");

function tracePng(buffer, opts) {
  return new Promise((resolve, reject) => {
    potrace.trace(buffer, opts, (err, svg) => (err ? reject(err) : resolve(svg)));
  });
}

function extractPathData(svg) {
  return [...svg.matchAll(/d="([^"]+)"/g)].map((m) => m[1]).join(" ");
}

(async () => {
  const img = await Jimp.read(SRC);
  img.resize(480, Jimp.AUTO);
  const W = img.bitmap.width;
  const H = img.bitmap.height;
  const cx = W / 2;
  const cy = H / 2;
  const data = img.bitmap.data;

  if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR);

  // Classify each source pixel, then build a black/white mask per layer
  const layerNames = ["circle", "initials", "flame"];
  const layers = {};
  for (const name of layerNames) {
    const mask = new Jimp(W, H, 0xffffffff);
    mask.scan(0, 0, W, H, function (x, y, idx) {
      const r = data[idx];
      const g = data[idx + 1];
      const b = data[idx + 2];
      const a = data[idx + 3];

      const isBackground = a < 60 || (r > 230 && g > 230 && b > 230);
      if (isBackground) return;

      const isOrange = g > 90 && r > 180; // flame tones
      const dist = Math.hypot(x - cx, y - cy);
      const inCenter = dist < W * 0.36; // initials live near the middle

      let hit = false;
      if (name === "flame") hit = isOrange;
      else if (name === "initials") hit = !isOrange && inCenter;
      else hit = !isOrange && !inCenter;

      if (hit) {
        this.bitmap.data[idx] = 0;
        this.bitmap.data[idx + 1] = 0;
        this.bitmap.data[idx + 2] = 0;
      }
    });
    layers[name] = mask;
    await mask.writeAsync(path.join(DEBUG_DIR, `layer-${name}.png`));
  }

  const traceOpts = { threshold: 128, turdSize: 10, optTolerance: 0.4 };
  const out = {};
  for (const [name, mask] of Object.entries(layers)) {
    const buf = await mask.getBufferAsync(Jimp.MIME_PNG);
    const svg = await tracePng(buf, traceOpts);
    out[name] = extractPathData(svg);
  }

  const ts = `// Auto-generated by scripts/trace-logo.js - traced from public/logo.png
// Do not edit by hand; re-run the script to regenerate.
export const LOGO_VIEWBOX = "0 0 ${W} ${H}";
export const CIRCLE_PATH = ${JSON.stringify(out.circle)};
export const INITIALS_PATH = ${JSON.stringify(out.initials)};
export const FLAME_PATH = ${JSON.stringify(out.flame)};
`;
  fs.writeFileSync(OUT, ts);

  console.log(`viewBox: 0 0 ${W} ${H}`);
  for (const [name, d] of Object.entries(out)) {
    console.log(`${name}: ${d.length} chars of path data`);
  }
})();
